name: ItemAunction
main: com.ericlam.main.ItemAunction
version: 1.0
authors: [Eric Lam]
soft-depend: [Vault]
api-version: 1.13
commands:
  twsell:
    description: sell command
  twbuy:
    description: buy command
  twget:
    description: get command